---
deployment:
  tasks:
      - export THEMES_DIR=/home/makecent/public_html/wp-content/themes
          - /bin/rm -rf "$THEMES_DIR/mcoh-theme"
              - /bin/cp -R "wordpress/themes/mcoh-theme" "$THEMES_DIR/"
                  - /bin/cp "prototypes/homepage-prototype.html" "$HOME/public_html/index.html"
