<!-- COMMUNITIES -->
<section class="section-communities">
  <div class="section-inner">
    <div class="section-header fade-in">
      <div>
        <span class="section-tag">Where You&#8217;ll Live</span>
        <h2 class="section-title">Every community has<br>its own <em>personality</em></h2>
      </div>
      <a href="<?php echo esc_url( home_url( '/communities' ) ); ?>" class="section-link">Full community guides</a>
    </div>
    <p class="communities-intro fade-in">Central Oregon isn&#8217;t just Bend. The region spans dozens of distinct neighborhoods and towns, each with a different pace, price point, and lifestyle. Start here.</p>
    <div class="communities-tabs fade-in" id="communityTabs">
      <div class="community-tab active" data-tab="bend">Bend Neighborhoods</div>
      <div class="community-tab" data-tab="greater-bend">Greater Bend Area</div>
      <div class="community-tab" data-tab="mountain">Mountain &amp; Resort Towns</div>
      <div class="community-tab" data-tab="high-desert">High Desert &amp; Regional</div>
    </div>

    <!-- TAB 1: Bend Neighborhoods -->
    <div class="communities-grid community-panel" data-panel="bend">
      <div class="community-card"><div class="community-card-name">Northwest Crossing</div><div class="community-card-type">Bend &middot; Northwest</div><div class="community-card-desc">Walkable grid streets, a neighborhood market, and strong community identity. Families, trail access, and the kind of neighborhood where people actually know each other.</div><div class="community-tags"><span class="community-tag">Walkable</span><span class="community-tag">Families</span><span class="community-tag">Trail access</span></div></div>
      <div class="community-card"><div class="community-card-name">Old Farm District</div><div class="community-card-type">Bend &middot; Southeast</div><div class="community-card-desc">Newer construction, larger lots, and quiet streets. Close to the Badlands Wilderness. Popular with families who want space without leaving Bend&#8217;s city limits.</div><div class="community-tags"><span class="community-tag">New builds</span><span class="community-tag">Spacious</span><span class="community-tag">Quiet</span></div></div>
      <div class="community-card"><div class="community-card-name">Awbrey Butte</div><div class="community-card-type">Bend &middot; Northwest</div><div class="community-card-desc">Elevated, panoramic, established. Views of the Cascades and Bend below. Mature trees, custom homes, and direct access to the Deschutes River Trail system.</div><div class="community-tags"><span class="community-tag">Views</span><span class="community-tag">Custom homes</span><span class="community-tag">Established</span></div></div>
      <div class="community-card"><div class="community-card-name">Midtown Bend</div><div class="community-card-type">Bend &middot; Central</div><div class="community-card-desc">Walkable to breweries, restaurants, and the river. Mix of remodeled bungalows and newer infill. The most urban Bend gets &#8212; which is still very Oregon.</div><div class="community-tags"><span class="community-tag">Urban</span><span class="community-tag">Walkable</span><span class="community-tag">Restaurants</span></div></div>
      <div class="community-card"><div class="community-card-name">River West</div><div class="community-card-type">Bend &middot; West Side</div><div class="community-card-desc">Established west-side Bend neighborhoods along the Deschutes corridor. Mix of mid-century homes and newer builds. Strong rental demand and central location.</div><div class="community-tags"><span class="community-tag">River access</span><span class="community-tag">Central</span><span class="community-tag">Established</span></div></div>
      <div class="community-card"><div class="community-card-name">Southeast Bend</div><div class="community-card-type">Bend &middot; Southeast</div><div class="community-card-desc">One of Bend&#8217;s fastest-growing quadrants. Newer neighborhoods, competitive entry prices relative to the west side, and easy access to the Badlands and east desert trails.</div><div class="community-tags"><span class="community-tag">Growing</span><span class="community-tag">Value</span><span class="community-tag">New builds</span></div></div>
      <div class="community-card"><div class="community-card-name">Mountain View</div><div class="community-card-type">Bend &middot; East Side</div><div class="community-card-desc">The most commuter-accessible part of Bend. Established neighborhoods, lower price points than the west side, and a straight shot to Highway 20 and Redmond.</div><div class="community-tags"><span class="community-tag">Accessible</span><span class="community-tag">Value</span><span class="community-tag">Established</span></div></div>
      <div class="community-card"><div class="community-card-name">Tetherow</div><div class="community-card-type">Bend &middot; Southwest</div><div class="community-card-desc">Resort community built around a David McLay Kidd golf course. Custom homes, Cascade views, and a community lodge. Southwest Bend&#8217;s premium address.</div><div class="community-tags"><span class="community-tag">Resort</span><span class="community-tag">Golf</span><span class="community-tag">Premium</span></div></div>
    </div>

    <!-- TAB 2: Greater Bend Area -->
    <div class="communities-grid community-panel" data-panel="greater-bend" style="display:none;">
      <div class="community-card"><div class="community-card-name">Redmond</div><div class="community-card-type">City &middot; 15 min north of Bend</div><div class="community-card-desc">Bend&#8217;s fastest-growing neighbor. Lower prices, more land, and a downtown that&#8217;s genuinely finding its stride. Roberts Field Airport access, industrial base, and a community identity that&#8217;s entirely its own.</div><div class="community-tags"><span class="community-tag">Value</span><span class="community-tag">Growth</span><span class="community-tag">Airport</span></div></div>
      <div class="community-card"><div class="community-card-name">Tumalo</div><div class="community-card-type">Unincorporated &middot; 10 min NW of Bend</div><div class="community-card-desc">Rural feel, Deschutes River access, and larger parcels with an easy commute to Bend. Agricultural roots with modern homestead energy. Acreage buyers come here first.</div><div class="community-tags"><span class="community-tag">Rural</span><span class="community-tag">Acreage</span><span class="community-tag">River access</span></div></div>
      <div class="community-card"><div class="community-card-name">Terrebonne</div><div class="community-card-type">Unincorporated &middot; 20 min north of Bend</div><div class="community-card-desc">Gateway community to Smith Rock State Park. Small-town character, agricultural land, and one of the most dramatic backyards in the state. Housing is still affordable here.</div><div class="community-tags"><span class="community-tag">Smith Rock</span><span class="community-tag">Small town</span><span class="community-tag">Affordable</span></div></div>
      <div class="community-card"><div class="community-card-name">Powell Butte</div><div class="community-card-type">Unincorporated &middot; 20 min SE of Redmond</div><div class="community-card-desc">Rural high desert community between Redmond and Prineville. Large parcels, sweeping open sky, and the kind of space that&#8217;s genuinely hard to find closer to Bend.</div><div class="community-tags"><span class="community-tag">Very rural</span><span class="community-tag">Farmland</span><span class="community-tag">Space</span></div></div>
      <div class="community-card"><div class="community-card-name">Alfalfa</div><div class="community-card-type">Unincorporated &middot; East of Bend</div><div class="community-card-desc">Remote high desert community on Bend&#8217;s eastern fringe. Large ranchland parcels, Badlands Wilderness adjacency, and the clearest night skies in Deschutes County.</div><div class="community-tags"><span class="community-tag">Remote</span><span class="community-tag">Ranchland</span><span class="community-tag">Dark skies</span></div></div>
    </div>

    <!-- TAB 3: Mountain & Resort Towns -->
    <div class="communities-grid community-panel" data-panel="mountain" style="display:none;">
      <div class="community-card"><div class="community-card-name">Sisters</div><div class="community-card-type">City &middot; 25 min west of Bend</div><div class="community-card-desc">Three Fingered Jack, North Sister, South Sister &#8212; all visible from main street. Boutique town character, mountain access, arts culture, and a summer event calendar that draws crowds from across the state.</div><div class="community-tags"><span class="community-tag">Mountain views</span><span class="community-tag">Arts</span><span class="community-tag">Charming</span></div></div>
      <div class="community-card"><div class="community-card-name">Sunriver</div><div class="community-card-type">Resort Community &middot; 15 min south of Bend</div><div class="community-card-desc">Purpose-built resort community with 35 miles of paved paths, its own nature center, pools, and a lodge. Strong vacation rental income. A market that performs year-round.</div><div class="community-tags"><span class="community-tag">Resort</span><span class="community-tag">Vacation rental</span><span class="community-tag">Family</span></div></div>
      <div class="community-card"><div class="community-card-name">La Pine</div><div class="community-card-type">City &middot; 30 min south of Bend</div><div class="community-card-desc">Oregon&#8217;s newest city. Larger lots, lower prices, and the Newberry National Volcanic Monument as a backyard. Deschutes River frontage, Paulina Lake day trips, and a community growing into itself.</div><div class="community-tags"><span class="community-tag">Affordable</span><span class="community-tag">Large lots</span><span class="community-tag">Newberry</span></div></div>
      <div class="community-card"><div class="community-card-name">Camp Sherman</div><div class="community-card-type">Unincorporated &middot; 45 min NW of Bend</div><div class="community-card-desc">A handful of cabins, a general store, and the spring-fed Metolius River &#8212; one of the most pristine rivers in the Pacific Northwest. Fly fishing country. Remote, intentional, and genuinely special.</div><div class="community-tags"><span class="community-tag">Remote</span><span class="community-tag">Fly fishing</span><span class="community-tag">Metolius River</span></div></div>
    </div>

    <!-- TAB 4: High Desert & Regional -->
    <div class="communities-grid community-panel" data-panel="high-desert" style="display:none;">
      <div class="community-card"><div class="community-card-name">Prineville</div><div class="community-card-type">City &middot; 35 min east of Bend &middot; Crook County</div><div class="community-card-desc">Central Oregon&#8217;s original pioneer town. Ochoco National Forest, thunderegg capital of the world, Prineville Reservoir, and a tight-knit community with more affordability than anywhere in Deschutes County.</div><div class="community-tags"><span class="community-tag">Affordable</span><span class="community-tag">Ochoco access</span><span class="community-tag">Growing</span></div></div>
      <div class="community-card"><div class="community-card-name">Madras</div><div class="community-card-type">City &middot; 45 min north of Bend &middot; Jefferson County</div><div class="community-card-desc">Jefferson County seat and Oregon&#8217;s solar eclipse capital &#8212; twice. Lake Billy Chinook access, Smith Rock within reach, and one of the best views of Mt Jefferson in the state.</div><div class="community-tags"><span class="community-tag">Affordable</span><span class="community-tag">Lake Billy Chinook</span><span class="community-tag">Agricultural</span></div></div>
      <div class="community-card"><div class="community-card-name">Warm Springs</div><div class="community-card-type">Tribal Nation &middot; 1 hr north of Bend</div><div class="community-card-desc">Home of the Confederated Tribes of Warm Springs. Kah-Nee-Ta Resort and Spa, Indian Head Casino, and deep cultural heritage. A significant destination in the regional experience.</div><div class="community-tags"><span class="community-tag">Kah-Nee-Ta</span><span class="community-tag">Cultural</span><span class="community-tag">Hot springs</span></div></div>
      <div class="community-card"><div class="community-card-name">Culver</div><div class="community-card-type">City &middot; 30 min north &middot; Jefferson County</div><div class="community-card-desc">Small agricultural community between Redmond and Madras. Lake Billy Chinook access, sweeping Cascade views, and the kind of quiet that has become genuinely rare in the region.</div><div class="community-tags"><span class="community-tag">Small town</span><span class="community-tag">Cascade views</span><span class="community-tag">Quiet</span></div></div>
      <div class="community-card"><div class="community-card-name">Maupin</div><div class="community-card-type">City &middot; 1 hr north &middot; Wasco County</div><div class="community-card-desc">White-water rafting capital of Oregon. The Deschutes River below Pelton Dam is world-class &#8212; and Maupin is the staging ground. Tiny town, big recreation identity.</div><div class="community-tags"><span class="community-tag">Rafting</span><span class="community-tag">Deschutes River</span><span class="community-tag">Outdoor</span></div></div>
    </div>
  </div>
</section>
